name: Demo Pipeline
 
on: push
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - run: ls -al
      - run: pwd
      
      - name: Checkout
        uses: actions/Checkout@v6.0.2 code

      - name: List all files
        run: ls-al
